---
name: "Java + Maven"
"on":
  push:
    branches:
    - "main"
  pull_request:
    branches:
    - "main"
jobs:
  build:
    runs-on: "ubuntu-latest"
    env:
      GH_TOKEN: "${{ secrets.GH_TOKEN }}"
    timeout-minutes: 360
    permissions:
      actions: "read"
      contents: "read"
      security-events: "write"
    steps:
    - uses: "actions/checkout@v4"
    - name: "Set up JDK 23"
      uses: "actions/setup-java@v4"
      with:
        distribution: "zulu"
        java-version: "23"
        java-package: "jdk"
        cache: "maven"
    - name: "Set up Maven"
      uses: "stCarolas/setup-maven@v5"
      with:
        maven-version: "3.9.9"
    - run: "mvn -s settings.xml spotless:check install"
    - name: "Initialize CodeQL"
      uses: "github/codeql-action/init@v3"
    - name: "Perform CodeQL Analysis"
      uses: "github/codeql-action/analyze@v3"
